[package]
name = "hotp"
version = "0.1.0"
authors = ["Prateek Kumar <prateek@prateekkumar.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.10.1"
sha-1 = "0.9.3"
